DEBUG = True
DISABLE_SENDER = True

MQTT_LISTENER_USERNAME = 'TestUsername'
MQTT_LISTENER_PASSWORD = 'Password2'
MQTT_LISTENER_HOSTNAME = '2fcf9ecce81b47d8b7884a7c158ea4a2.s1.eu.hivemq.cloud'
MQTT_LISTENER_PORT = 8883
MQTT_LISTENER_TOPICS = ['my/test/topic']

MQTT_SENDER_USERNAME = ''
MQTT_SENDER_PASSWORD = ''
MQTT_SENDER_HOSTNAME = ''
MQTT_SENDER_PORT = 0
MQTT_SENDER_TOPIC = ''